language: node_js
node_js:
    - node
before_install:
    - npm install webber
    - npm install builder
    - npm install tagger
script:
    - npm run tagger
    - npm run builder
    - npm run webber
after_success:
    - chmod +x .travis/push.sh
    - sudo .travis/push.sh
env:
  global: 
  - secure: E+2E3M4ubbMPgZLlO3uR+2ojE8+5V8vWvh+U3tK6DmLMegGgR14lIYMK7v0RhZ5Oj0stF1lRDLTUrioZwygw4H5D/1bE4H7f92KffopRz8KL/zpvweNcxrAbLpD40WfzCgVlq8A8kM1U9LOVYVNF5s9WUomH6c64bVda72bX0W0lILjoMEroLzFDE4sQ7NFyLnX+S/3xF0b60bvDRLUvdnoDVfNODsXaBwYCFfC2BwdI1tw62KkNG17QM/bL1Gb8OG7vE37OwE9l7NUM3+R1o+YKIGRvIMkyq1msKGfj/pVS8McbA61dYvpuYf9sxvXOgQcbdNn6Gzofs48g2QguNfJuBEv2kohzQ7yQIgBfdzBxBiAPfROJjwzs0PoVZjmCicBMAlZL/unJC3MBKIkawz1vENlnYgM601slR+5od+6IhoVNXA2wlz89+RHQ/Gn9iLlX/611nzgjaObpl6P/8NbwJfUnG5vYcN1MDXpEbsBbb5rUeC0J1FChWV7O5VcgT2/p7Xgc7i9T2H8bSZYjXEhOJ6vWToRTSl0MNUa/PY5+KmNF8HxstTSwhPHF0Eh/tFpprTrBjp0nRNa6wdPhPI8XdnDjqNFw/VTNilutF4RAfwUEBRhZeuK1bNwpuakzwMWGUUazOm+nfxND5i6TYT4haP1iuyv3kVqvgDXgNbY=
