language: node_js
node_js:
    - node
before_install:
    - npm install webber
    - npm install builder
    - npm install tagger
script:
    - npm run tagger
    - npm run builder
    - npm run webber
after_success:
    - chmod +x .travis/push.sh
    - sudo .travis/push.sh
env:
  global: 
    - secure: "dgdJT6owa/NdtXb+41vDsQPNbNAlela/CyoHrTtJqMZjH3UzoYdqUeMd+qJ+T3+yneUZ3ZPdvdrkGhFX3cHwqFFcShT/9abpXVFMvExE6BHhx7Z/ZSfNRfEsA7uowMd6FrI5QXwRMefP74eUlA2pc0Ky3miwwX1GYLWO0zrGTzwzamjHfLxOOgiln++iqRH1IEejuAnhBK+8WjL8OxP6g0VG6U0ofApf96tnf8Z/4OUDsHlKzUjSuPszJsD1xCXUjx+J/C8fOuGif8b+oXWQPqJVi5E3FKMCoN0wS0XBSch7HNDwq7PhSK7TS6PKP6kn9NtaHo8HAEfzl6w41ilBBZgY6FYjC6qQDVIYjndNxRa5EiHOZUeFG7Ejg+jlSQSaCuvzXHKMtSZoHHboG652IWeXFWEvc+d4fFKWbexAE7k6CuQayPRUzWy1FPqRnTkkKfwCgUW0DHhltQPh3sski1iBOqeNE0vjn4f2nSS36R9jpkVmc+j2YZU6jqGrjavdtXQQmppPEU9O6k6ZNCB5yzPvnM3e9191ujhqC9RJphiEXWMDZ7zmACn1vEp3Py6vRqOu2HBhYbtgd10DGgTtXfvu4GBY7l/AZqoIC+EeFxqFJyryV0cnsEeo19NycnknBD1uK8zbeYPWmjeySVBCyy3gliq/dsxxDMTPBUUSSow="
